---
# NIOS onedb analysis report configuration file
version: 0.0.9
# Last updated: 20210513
# Author: Chris Marrison

# Report Output (future use)
output_path: 
zip_reports: False

report_sections:
  - processed
  - collected
  - counters
  - features
  - member_counts
  - summary

# Define Keys for uniqueness matching in summary reports
summary_items:
  DHCP_Options:
    name: DHCP_Options
    keys:
      - STATUS
      - OPTIONSPACE
      - OPTIONCODE
  Networks:
    name: IPAM_Networks
    keys:
      - STATUS
      - CIDR

# Currently Not used
Incompatible Features:
  - DHCPv6:
      section: features
  - BOOTP:
      section: collected
      objects: 
        - .com.infoblox.dns.cluster_dhcp_properties
        - .com.infoblox.dns.member_dhcp_properties
        - .com.infoblox.dns.network
      properties: 
      value: 

