---
# NIOS onedb analysis report configuration file
version: 0.0.5
# Last updated: 20210406
# Author: Chris Marrison
report_sections:
  - processed
  - collected
  - counters
  - features
  - member_counts
  - summary

summary_items:
  dhcpoption:
    name: DHCP_Options
    keys: 
      - STATUS
      - OPTIONSPACE
      - OPTIONCODE
  dhcpnetwork:
    name: IPAM_Networks
    keys:
      - STATUS


Incompatible Features:
  - DHCPv6:
      section: features
  - BOOTP:
      section: collected
      objects: 
        - .com.infoblox.dns.cluster_dhcp_properties
        - .com.infoblox.dns.member_dhcp_properties
        - .com.infoblox.dns.network
      properties: 
      value: 

