---
# NIOS onedb analysis report configuration file
version: 0.0.7
# Last updated: 20210511
# Author: Chris Marrison
report_sections:
  - processed
  - collected
  - counters
  - features
  - member_counts
  - summary

summary_items:
  DHCP_Options:
    name: DHCP_Options
    keys:
      - STATUS
      - OPTIONSPACE
      - OPTIONCODE
  Networks:
    name: IPAM_Networks
    keys:
      - STATUS
      - CIDR

# Currently Not used
Incompatible Features:
  - DHCPv6:
      section: features
  - BOOTP:
      section: collected
      objects: 
        - .com.infoblox.dns.cluster_dhcp_properties
        - .com.infoblox.dns.member_dhcp_properties
        - .com.infoblox.dns.network
      properties: 
      value: 

